return {
    transitionSpeed = 14,
    scoreStateDuration = 0.34,
    scorePulseDuration = 0.20,
    selectPulseDuration = 0.16,
    tiltShear = 0.018,
    tiltVerticalScale = 0.72,
    debugToggleKey = "f7",
    rollOrder = { "foil", "holographic", "polychrome" },
    effects = {
        foil = {
            shader = "shaders/card_foil.glsl",
            idleStrength = 0.18,
            hoverStrength = 0.88,
            selectedStrength = 1.08,
            scoringStrength = 1.32,
            speed = 0.86,
            shopChance = 0.075,
            shopLabel = "FOIL",
            shopText = "Foil: +50 sát thương cố định khi chấm lá.",
            score = { damage = 50, chips = 0, mult = 0, auraMultiplier = 1 },
            beamColor = { 0.70, 0.86, 1.0 },
        },
        holographic = {
            shader = "shaders/card_holographic.glsl",
            idleStrength = 0.16,
            hoverStrength = 0.92,
            selectedStrength = 1.10,
            scoringStrength = 1.35,
            speed = 0.62,
            shopChance = 0.035,
            shopLabel = "HOLOGRAPHIC",
            shopText = "Holographic: +10 Cường hóa (Mult) khi chấm lá.",
            score = { chips = 0, mult = 10, auraMultiplier = 1 },
            beamColor = { 0.72, 0.50, 1.0 },
        },
        polychrome = {
            shader = "shaders/card_polychrome.glsl",
            idleStrength = 0.12,
            hoverStrength = 0.78,
            selectedStrength = 0.98,
            scoringStrength = 1.20,
            speed = 0.40,
            shopChance = 0.01,
            shopLabel = "POLYCHROME",
            shopText = "Polychrome: nhân x1.5 Aura cuối khi chấm lá.",
            score = { chips = 0, mult = 0, auraMultiplier = 1.5 },
            beamColor = { 1.0, 0.56, 0.86 },
        },
    },
}
