-- Authored by actual equipment role. Every ordinary finished item has one acyclic recipe.
-- tier: 1 practical / 2 refined / 3 advanced / 4 master / 5 legendary.
return {
 {id="crafted_guard",tier=1,fee=4,ingredients={"basic_bandage","basic_plate"},reason="Lót vải hồi phục bên trong tấm giáp."},
 {id="crafted_runner",tier=1,fee=4,ingredients={"basic_herb","basic_lace"},reason="Ủng buộc chắc và túi dược rễ cho người chạy đường dài."},
 {id="crafted_bulwark",tier=2,fee=7,ingredients={"crafted_guard","basic_leather","basic_spur"},reason="Gia cố áo hộ mệnh để hành quân nhanh trong giáp."},
 {id="crafted_medic",tier=2,fee=7,ingredients={"crafted_guard","basic_salve","basic_pouch"},reason="Nâng bộ bảo hộ thành túi quân y có ngăn tiền tiếp tế."},
 {id="crafted_caravan",tier=3,fee=10,ingredients={"crafted_bulwark","basic_chain","basic_weight"},reason="Giáp hành quân kết hợp khóa xích và đối trọng thương đội."},
 {id="crafted_courier",tier=3,fee=10,ingredients={"crafted_runner","basic_feather","basic_stamp"},reason="Đồ người chạy tin được chuẩn hóa cho đường giao thương."},
 {id="gem_fire",tier=1,fee=4,ingredients={"basic_plate","basic_spur"},reason="Mũi thép thúc lực cho đòn tiên phong."},
 {id="gem_blast",tier=1,fee=5,ingredients={"basic_plate","basic_spur","basic_spur"},reason="Ba bộ phận chịu lực tạo nhịp tam kích."},
 {id="ward_stone",tier=1,fee=4,ingredients={"basic_plate","basic_leather"},reason="Thép và lớp da giảm chấn cho thế thủ ít quân."},
 {id="mirror_adjacent",tier=2,fee=6,ingredients={"basic_plate","basic_weight","basic_lace"},reason="Bề mặt thép cân chỉnh để nối hiệu ứng giữa hai lá kề."},
 {id="storm_eye",tier=2,fee=6,ingredients={"basic_lace","basic_spur","basic_feather"},reason="Ba linh kiện tốc phối hợp một luồng đồng chất."},
 {id="lucky_coin",tier=2,fee=6,ingredients={"basic_pouch","basic_weight","basic_stamp"},reason="Đồng tiền được cân, đóng dấu và cất giữ."},
 {id="vitality_gem",tier=2,fee=6,ingredients={"basic_herb","basic_salve","basic_bandage"},reason="Cô đặc bộ dược cứu thương cho lúc máu thấp."},
 {id="blood_ring",tier=3,fee=9,ingredients={"vitality_gem","basic_chain","basic_spur"},reason="Khóa sức sống trong vòng kim loại để đổi máu lấy sát thương."},
 {id="itm_abacus",tier=2,fee=5,ingredients={"basic_weight","basic_plate","basic_pouch"},reason="Cân và hạt tiền tạo dụng cụ tính sức mạnh quân thấp."},
 {id="itm_twinfang",tier=3,fee=9,ingredients={"gem_blast","basic_spur","basic_chain"},reason="Từ nhịp tam kích rèn thành cặp nanh liên kết cùng rank."},
 {id="itm_wayfarer",tier=2,fee=6,ingredients={"basic_lace","basic_feather","basic_pouch"},reason="Dụng cụ lữ hành nối bước quân theo rank liền nhau."},
 {id="itm_prism",tier=3,fee=9,ingredients={"mirror_adjacent","basic_feather","basic_weight"},reason="Gương đã cân chỉnh được mài thành lăng kính đa chất."},
 {id="itm_hourglass",tier=2,fee=6,ingredients={"ward_stone","basic_plate","basic_lace"},reason="Bộ thủ thế được căn theo nhịp tốc của đối thủ."},
 {id="itm_miser",tier=3,fee=9,ingredients={"lucky_coin","basic_weight","basic_stamp"},reason="Đồng tiền Át trở thành chìa khóa kho vàng tích trữ."},
 {id="itm_quiver",tier=2,fee=6,ingredients={"basic_leather","basic_feather","basic_plate"},reason="Ống da và tên thép dự trữ cho quân còn giữ trên tay."},
 {id="itm_anvil",tier=3,fee=10,ingredients={"gem_fire","ward_stone","basic_chain"},reason="Đe kết hợp rèn công, thủ và khóa hốc trang bị."},
 {id="itm_crown",tier=2,fee=6,ingredients={"basic_chain","basic_weight","basic_herb"},reason="Vương miện cân sức người chỉ huy độc hành."},
 {id="itm_root",tier=3,fee=9,ingredients={"crafted_guard","basic_herb","basic_herb","basic_weight"},reason="Bảo hộ sống được nuôi bằng hai rễ, lớn theo tiến hóa."},
 {id="itm_capacitor",tier=3,fee=10,ingredients={"storm_eye","basic_chain","basic_weight"},reason="Luồng sét được nhốt trong ba khoang tích điện."},
 {id="itm_counterweight",tier=4,fee=14,ingredients={"blood_ring","crafted_bulwark","basic_chain"},reason="Phản đòn từ máu mất đòi hỏi cả huyết khí lẫn giáp chịu lực."},
 {id="itm_ledger",tier=3,fee=10,ingredients={"itm_miser","basic_weight","basic_pouch"},reason="Ngân khố và sổ đầu tư lưu các nấc phát triển vĩnh viễn."},
 {id="itm_oar",tier=2,fee=6,ingredients={"basic_leather","basic_plate","basic_lace"},reason="Mái chèo chuyển thế kết hợp sức công và giáp."},
 {id="itm_hourhand",tier=3,fee=10,ingredients={"itm_hourglass","basic_spur","basic_spur"},reason="Cơ cấu hai nhịp canh gác chịu được hai đòn quái."},
 {id="itm_bloodvial",tier=4,fee=14,ingredients={"blood_ring","basic_salve","basic_salve","basic_weight"},reason="Bình huyết tế cần vòng khóa, hai phần cao và khoang đo giọt."},
 {id="itm_relay",tier=3,fee=10,ingredients={"itm_quiver","basic_chain","basic_chain","basic_lace"},reason="Hai mắt xích chuyển lực từ vũ khí dự trữ sang quân tiếp theo."},
 {id="itm_lockbox",tier=3,fee=10,ingredients={"ward_stone","basic_weight","basic_chain"},reason="Giáp được cân và khóa để đổi thành lực công."},
 {id="itm_bell",tier=4,fee=12,ingredients={"vitality_gem","basic_plate","basic_weight","basic_feather"},reason="Chuông dưỡng nhịp tĩnh lặng cần sức sống và cơ cấu cân nhịp."},
 {id="itm_pendulum",tier=2,fee=7,ingredients={"gem_fire","basic_plate","basic_lace"},reason="Quả lắc đổi công hoặc thủ theo số quân giữa hai tay."},
 {id="void_catalyst",tier=5,fee=22,ingredients={"itm_capacitor","itm_bell","itm_prism","basic_stamp"},reason="Xúc tác hư không hội tụ năng lượng tích, nhịp ổn định và lăng kính đa chất."},
}
