-- Five distinct expedition tools per tier. Costs come from their real recipes.
local T={definitions={}}
local function game(ctx) return require("src.chest_depth").game(ctx) end
local function health(ctx) local g=game(ctx);return (g.playerHp or 100)/math.max(1,g.maxPlayerHp or 100) end
local function distinct(cs,field) local seen,n={},0;for _,c in ipairs(cs) do if not seen[c[field]] then seen[c[field]]=true;n=n+1 end end;return n end
local function balanced(cs) local n=0;for _,c in ipairs(cs) do if c.rank%2==0 then n=n+1 end end;return n*2==#cs end
local function spend(ctx,n)
 local g=game(ctx);local previewOnly=ctx.preview and not ctx.depthGame
 local spent=previewOnly and (ctx.tierGoldSpent or 0) or 0
 if (g.gold or 0)-spent<n then return false end
 if previewOnly then ctx.tierGoldSpent=spent+n else g.gold=g.gold-n end
 return true
end
local function speed(c,ctx) return require("src.deck").getCardAttackSpeed(c)>((ctx.monster or {}).attackSpeed or 1) end
local function add(id,name,tier,p,desc,concept,effect)
 local d={id=id,name=name,craftTier=tier,cost=({4,5,6,7,8})[tier],slotsNeeded=tier==5 and 2 or 1,
  rarity=({"common","uncommon","rare","epic","legendary"})[tier],params=p,descriptionTemplate=desc,
  concept=concept,artConcept=concept,attackSpeed=p.speed or 0,color=({{.6,.7,.7,1},{.35,.8,.65,1},{.4,.65,1,1},{.8,.45,1,1},{1,.8,.35,1}})[tier]}
 d.onCardScore=function(c,cs,i,ctx) return effect(c,cs,i,ctx or {},p) end
 T.definitions[#T.definitions+1]=d
end
add("itm_fieldneedle","Kim Khâu Dã Chiến",1,{heal=3,armor=2},"+{armor} Giáp; thêm {heal} HP nếu HP dưới 75%.","One thick curved silver field needle threading green linen through a torn iron-lined bandage, on mossy forest infirmary stone.",function(c,cs,i,ctx,p) return {addArmor=p.armor,healHp=health(ctx)<.75 and p.heal or 0} end)
add("itm_heelhook","Móc Gót Tiên Phong",1,{speed=2,chips=16},"+{speed} Tốc khi gắn. Đứng đầu vùng tính điểm: +{chips} ST.","One hooked iron heel cleat strapped to a single weathered expedition boot, biting into a blue glacial trail, clear hook silhouette.",function(c,cs,i,ctx,p) if i==1 then return {addChips=p.chips} end end)
add("itm_surveyhammer","Búa Thăm Dò",1,{chips=14,armor=3},"+{chips} ST; rank 2–6 nhận thêm {armor} Giáp.","One short rugged survey hammer with a broad steel head and leather grip beside freshly split ore on bone gold desert rock.",function(c,cs,i,ctx,p) return {addChips=p.chips,addArmor=c.rank>=2 and c.rank<=6 and p.armor or 0} end)
add("itm_rationseal","Niêm Tiếp Tế",1,{armor=3,gold=1},"+{armor} Giáp. Đứng đầu vùng đúng 3 lá tính điểm: +{gold} Vàng.","One iron supply clasp sealing a compact leather ration roll, a single antique coin tucked under the clasp, coastal expedition camp.",function(c,cs,i,ctx,p) return {addArmor=p.armor,addGold=#cs==3 and i==1 and p.gold or 0} end)
add("itm_balancebrace","Nẹp Cân Bằng",1,{chips=20,armor=3},"Số rank chẵn/lẻ bằng nhau: +{chips} ST; nếu không: +{armor} Giáp.","One symmetrical hinged steel wrist brace with two equal broad bronze counterplates on a frost dusted expedition table.",function(c,cs,i,ctx,p) return balanced(cs) and {addChips=p.chips} or {addArmor=p.armor} end)
add("itm_triageclasp","Khóa Cứu Thương",2,{heal=5,armor=7},"HP tối đa 35%: hồi {heal} HP; nếu không: +{armor} Giáp.","One emerald glass emergency clasp on a folded white field dressing, its protective steel jaws opening in a ruined green infirmary.",function(c,cs,i,ctx,p) return health(ctx)<=.35 and {healHp=p.heal} or {addArmor=p.armor} end)
add("itm_windspindle","Trục Cuốn Gió",2,{speed=2,mult=5},"+{speed} Tốc khi gắn. Rank cao hơn lá tính điểm ngay trước: +{mult} Cường hóa.","One silver wind spindle with a tall tapering central axle and a tightly wound pale blue cord on a coastal cliff workbench.",function(c,cs,i,ctx,p) if cs[i-1] and c.rank>cs[i-1].rank then return {addMult=p.mult} end end)
add("itm_shieldsuture","Kim Đan Giáp",2,{armor=10,heal=3},"Ít nhất 3 lá tính điểm: +{armor} Giáp; nếu không: hồi {heal} HP.","One heavy steel weaving shuttle joining three large chainmail links over green padding on a glacial ruined forge.",function(c,cs,i,ctx,p) return #cs>=3 and {addArmor=p.armor} or {healHp=p.heal} end)
add("itm_tollscale","Cân Trạm Thu",2,{chips=20,gold=1},"+{chips} ST; đang giữ dưới 12 Vàng: thêm {gold} Vàng.","One compact antique brass toll scale with a closed iron weighing pan and one copper coin, sunlit ruined desert caravan checkpoint.",function(c,cs,i,ctx,p) return {addChips=p.chips,addGold=(game(ctx).gold or 0)<12 and p.gold or 0} end)
add("itm_scoutlens","Kính Trinh Sát",2,{chips=10,cap=40},"Mỗi rank khác nhau trong vùng tính điểm: +{chips} ST, tối đa {cap}.","One rugged brass monocular scouting lens with four broad glass facets, overlooking layered deep blue continental coast cliffs.",function(c,cs,i,ctx,p) return {addChips=math.min(p.cap,p.chips*distinct(cs,"rank"))} end)
add("itm_redoubtstandard","Cờ Pháo Đài",3,{armor=14,chips=40},"Chậm hơn quái mục tiêu: +{armor} Giáp; nếu không: +{chips} ST.","One physical iron fortress standard with a broad worn navy swallowtail cloth mounted on a compact stone parapet in a glacial pass.",function(c,cs,i,ctx,p) return require("src.deck").getCardAttackSpeed(c)<((ctx.monster or {}).attackSpeed or 1) and {addArmor=p.armor} or {addChips=p.chips} end)
add("itm_lifebasin","Bát Dưỡng Sinh",3,{heal=7,chips=20},"+{chips} ST; giữ ít nhất 2 lá trên tay: hồi thêm {heal} HP.","One broad jade green medicinal bowl containing luminous sap and two intact leaves, on a root-wrapped ruined forest altar.",function(c,cs,i,ctx,p) return {addChips=p.chips,healHp=#(ctx.hand or {})>=2 and p.heal or 0} end)
add("itm_dualgear","Bánh Răng Song Nhịp",3,{speed=3,mult=9},"+{speed} Tốc khi gắn. Số rank chẵn/lẻ bằng nhau: +{mult} Cường hóa.","One tangible pair of interlocking large silver and antique brass gears, clearly one assembled mechanism on blue mountain forge stone.",function(c,cs,i,ctx,p) if balanced(cs) then return {addMult=p.mult} end end)
add("itm_exchangehorn","Tù Và Đổi Chợ",3,{goldCost=2,chips=42,armor=10},"Tự trả {goldCost} Vàng khi tính điểm: +{chips} ST và +{armor} Giáp. Thiếu Vàng không kích hoạt.","One broad bronze caravan trading horn with a rugged leather coin collar, lying on a desert market slab beside two copper coins.",function(c,cs,i,ctx,p) if spend(ctx,p.goldCost) then return {addChips=p.chips,addArmor=p.armor} end end)
add("itm_formationpin","Trâm Liên Đội",3,{mult=11},"Có hai lá tính điểm kề hai bên, cả hai khác chất với lá này: +{mult} Cường hóa.","One large three-pronged expedition cloak pin linking a green central gemstone to two blue and red stone clasps, quiet coastal ruins.",function(c,cs,i,ctx,p) if cs[i-1] and cs[i+1] and cs[i-1].suit~=c.suit and cs[i+1].suit~=c.suit then return {addMult=p.mult} end end)
add("itm_oathmantle","Áo Choàng Lời Thề",4,{armor=22,heal=9},"HP ít nhất 75%: +{armor} Giáp; nếu không: hồi {heal} HP.","One tangible heavy ivory and silver oath mantle hanging from an abandoned Western knight armor stand in a cold ruined chapel, green inner lining.",function(c,cs,i,ctx,p) return health(ctx)>=.75 and {addArmor=p.armor} or {healHp=p.heal} end)
add("itm_tempestwinch","Tời Bão",4,{speed=4,mult=14},"+{speed} Tốc khi gắn. Nhanh hơn quái mục tiêu: +{mult} Cường hóa.","One powerful iron storm winch with a large navy cable drum hauling a taut silver rope through coastal wind, broad readable mechanism on a sea cliff.",function(c,cs,i,ctx,p) if speed(c,ctx) then return {addMult=p.mult} end end)
add("itm_reprisallance","Thương Phản Chấn",4,{armor=8,damagePercent=7,cap=28},"+{armor} Giáp. Mỗi đòn quái bị chặn hoàn toàn từ tay trước: +{damagePercent}% sát thương, tối đa {cap}%.","One long heavy silver recoil lance with a broad spring-loaded guard, planted in a cracked ice shield slab showing restrained rebound arcs.",function(c,cs,i,ctx,p) local n=((game(ctx).depthCombat or {}).blocked or 0);return {addArmor=p.armor,extraDamagePct=math.min(p.cap,n*p.damagePercent)/100} end)
add("itm_escrowseal","Ấn Tín Ký Quỹ",4,{goldCost=3,heal=10,armor=16},"Tự trả {goldCost} Vàng khi tính điểm: hồi {heal} HP và +{armor} Giáp. Thiếu Vàng không kích hoạt.","One large tangible gold escrow signet in a stout iron housing, securing three antique coins under protective green glass on a desert merchant altar.",function(c,cs,i,ctx,p) if spend(ctx,p.goldCost) then return {healHp=p.heal,addArmor=p.armor} end end)
add("itm_crescentvise","Ê-tô Trăng Khuyết",4,{chips=72,mult=9},"Đúng 2 hoặc 4 lá tính điểm: +{chips} ST; nếu không: +{mult} Cường hóa.","One broad crescent-shaped silver smithing vise with two opposing massive jaws framing a quiet violet eclipse, on Western void forge stone.",function(c,cs,i,ctx,p) return (#cs==2 or #cs==4) and {addChips=p.chips} or {addMult=p.mult} end)
add("itm_worldanchor","Mỏ Neo Đại Lục",5,{armor=28,chips=80,fallbackArmor=14,fallbackChips=35},"Chiếm 2 hốc. Đổi thế đánh so với tay trước: +{armor} Giáp, +{chips} ST; tay đầu/lặp thế: +{fallbackArmor} Giáp, +{fallbackChips} ST.","One colossal tangible ancient iron continent anchor with broad broken-stone flukes holding two opposing sea currents at a ruined deep navy coastal gateway.",function(c,cs,i,ctx,p) local last=(game(ctx).depthCombat or {}).lastType;return last and last~=ctx.depthHandType and {addArmor=p.armor,addChips=p.chips} or {addArmor=p.fallbackArmor,addChips=p.fallbackChips} end)
add("itm_phoenixcradle","Nôi Phượng Hỏa",5,{heal=16,damagePercent=25,chips=90},"Chiếm 2 hốc. HP tối đa 30%: hồi {heal} HP, +{damagePercent}% sát thương; nếu không: +{chips} ST.","One tangible phoenix-shaped bronze cradle cupping a single red medicinal ember, dominant broad wings carved from metal, dark volcanic expedition sanctuary.",function(c,cs,i,ctx,p) return health(ctx)<=.3 and {healHp=p.heal,extraDamagePct=p.damagePercent/100} or {addChips=p.chips} end)
add("itm_horizonengine","Động Cơ Chân Trời",5,{speed=6,chips=100,armor=24},"Chiếm 2 hốc. +{speed} Tốc khi gắn. Nhanh hơn quái: +{chips} ST; nếu không: +{armor} Giáp.","One tangible ancient expedition propulsion engine with a single broad silver turbine and restrained blue core, set on a high glacial cliff facing a vast horizon.",function(c,cs,i,ctx,p) return speed(c,ctx) and {addChips=p.chips} or {addArmor=p.armor} end)
add("itm_sovereignscale","Cân Vương Quyền",5,{goldCost=4,mult=24,armor=24,chips=60},"Chiếm 2 hốc. Tự trả {goldCost} Vàng: +{mult} Cường hóa và +{armor} Giáp; thiếu Vàng: +{chips} ST.","One monumental tangible antique golden sovereign balance with a solid armored pan opposite a large coin ingot, clear balanced silhouette in Western bone gold desert royal ruins.",function(c,cs,i,ctx,p) return spend(ctx,p.goldCost) and {addMult=p.mult,addArmor=p.armor} or {addChips=p.chips} end)
add("itm_concordharp","Hạc Cầm Bốn Xứ",5,{chips=110,mult=18,perChips=18,perMult=3},"Chiếm 2 hốc. Đủ 4 chất tính điểm: +{chips} ST, +{mult} Cường hóa; nếu không: mỗi chất +{perChips} ST, +{perMult} Cường hóa.","One large tangible Western golden harp with four broad distinct gemstone-tipped strings in red, green, ice blue and antique gold, standing in ancient forest continental alliance ruins, restrained light.",function(c,cs,i,ctx,p) local n=distinct(cs,"suit");return n>=4 and {addChips=p.chips,addMult=p.mult} or {addChips=n*p.perChips,addMult=n*p.perMult} end)
return T
